# Generated by Django 4.2.1 on 2023-07-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetails',
            name='remove_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imagedetails',
            name='remove_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
